<?php

use Illuminate\Support\Facades\Session;

function send_notif($to, $notif)
{

    $apikey = "AAAA_tVP5ao:APA91bFk70jq2AuIaA1r5DSkqmh926DFWNUhQb9bsdTxRD42utZK4Fj8x5U5vilPI91iMJokZwnaY0iwt-fZUcTusXw1Rg4E0V7GNm6SbKGsr6MpXkGw6C6hrOCKTHgNCnpORyTFVZgW";

    // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
    $ch = curl_init();

    $url = "https://fcm.googleapis.com/fcm/send";
    $fields = json_encode(array('to' => $to, 'notification' => $notif));

    curl_setopt($ch, CURLOPT_URL, $url);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_POST, 1);
    curl_setopt($ch, CURLOPT_POSTFIELDS, $fields);

    $headers = array();
    $headers[] = 'Authorization: key =' . $apikey;
    $headers[] = 'Content-Type: application/json';
    curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

    $result = curl_exec($ch);
    if (curl_errno($ch)) {
        echo 'Error:' . curl_error($ch);
    }
    curl_close($ch);
}
